# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoadLandingPage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loadLandingPage(self):
    # Test name: LoadLandingPage
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.usaspending.gov/")
    # 2 | setWindowSize | 2335x1174 | 
    self.driver.set_window_size(2335, 1174)
    # 3 | mouseOver | css=.button__lg:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".button__lg:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | css=.button__lg:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".button__lg:nth-child(1)").click()
    # 5 | click | id=fy2008 | 
    self.driver.find_element(By.ID, "fy2008").click()
    # 6 | mouseOver | id=fy2008 | 
    element = self.driver.find_element(By.ID, "fy2008")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | id=fy2008 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | click | css=.sidebar-bottom-submit .reset-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-bottom-submit .reset-button").click()
    # 9 | click | id=fy2023 | 
    self.driver.find_element(By.ID, "fy2023").click()
    # 10 | click | css=.sidebar-bottom-submit .reset-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-bottom-submit .reset-button").click()
    # 11 | click | css=.left-fy > div:nth-child(2) .fy-option-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".left-fy > div:nth-child(2) .fy-option-wrapper").click()
    # 12 | click | id=fy2022 | 
    self.driver.find_element(By.ID, "fy2022").click()
    # 13 | click | id=fy2021 | 
    self.driver.find_element(By.ID, "fy2021").click()
    # 14 | mouseOver | id=fy2021 | 
    element = self.driver.find_element(By.ID, "fy2021")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | id=fy2021 | 
    self.driver.find_element(By.ID, "fy2021").click()
    # 16 | doubleClick | id=fy2021 | 
    element = self.driver.find_element(By.ID, "fy2021")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 17 | mouseOut | id=fy2021 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 18 | click | id=fy2020 | 
    self.driver.find_element(By.ID, "fy2020").click()
    # 19 | click | id=fy2020 | 
    self.driver.find_element(By.ID, "fy2020").click()
    # 20 | doubleClick | id=fy2020 | 
    element = self.driver.find_element(By.ID, "fy2020")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 21 | click | id=fy2019 | 
    self.driver.find_element(By.ID, "fy2019").click()
    # 22 | click | id=fy2019 | 
    self.driver.find_element(By.ID, "fy2019").click()
    # 23 | doubleClick | id=fy2019 | 
    element = self.driver.find_element(By.ID, "fy2019")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 24 | click | id=fy2018 | 
    self.driver.find_element(By.ID, "fy2018").click()
    # 25 | click | id=fy2018 | 
    self.driver.find_element(By.ID, "fy2018").click()
    # 26 | doubleClick | id=fy2018 | 
    element = self.driver.find_element(By.ID, "fy2018")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 27 | click | id=fy2017 | 
    self.driver.find_element(By.ID, "fy2017").click()
    # 28 | click | id=fy2017 | 
    self.driver.find_element(By.ID, "fy2017").click()
    # 29 | doubleClick | id=fy2017 | 
    element = self.driver.find_element(By.ID, "fy2017")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 30 | click | css=.left-fy > div:nth-child(1) .fy-option-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".left-fy > div:nth-child(1) .fy-option-wrapper").click()
    # 31 | click | css=.sidebar-bottom-submit .submit-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-bottom-submit .submit-button").click()
    # 32 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 33 | waitForElementPresent | linkText=HT940216C0001 | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "HT940216C0001")))
  
