# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMainNav():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mainNav(self):
    self.driver.get("https://www.usaspending.gov/")
    self.driver.set_window_size(1335, 1143)
    assert self.driver.title == "Government Spending Open Data | USAspending"
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Search Award Data")))
    element = self.driver.find_element(By.CSS_SELECTOR, ".button__lg:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".navbar-item-title-1")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".navbar-item-title-2")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".navbar-item-title-3")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Search Award Data")))
    self.driver.find_element(By.LINK_TEXT, "Search Award Data").click()
    element = self.driver.find_element(By.LINK_TEXT, "Search Award Data")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Advanced Search"
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#table > .label")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".usa-da-icon-calendar path")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#map > .label")))
    WebDriverWait(self.driver, 0.03).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#rank > .label")))
  
